name: firebase_core_desktop
description: Desktop implementation of firebase_core
homepage: https://firebase.flutter.dev
repository: https://github.com/invertase/flutterfire_dart
version: 0.1.1-dev.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  firebase_core_platform_interface: ^4.0.1
  flutterfire_core_dart: ^0.1.1-dev.0
  flutter:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  firebase_core:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  plugin_platform_interface: ^2.0.0

flutter:
  plugin:
    implements: firebase_core
    platforms:
      macos:
        dartPluginClass: FirebaseCore
        pluginClass: none
      linux:
        dartPluginClass: FirebaseCore
        pluginClass: none
      windows:
        dartPluginClass: FirebaseCore
        pluginClass: none

