name: firebase_auth_desktop
description: Desktop implementation of firebase_auth
homepage: https://firebase.flutter.dev
repository: https://github.com/invertase/flutterfire_dart
version: 0.1.1-dev.0

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  firebase_auth: ^3.1.4
  firebase_auth_platform_interface: ^6.1.2
  firebase_core: ^1.8.0
  flutter:
    sdk: flutter
  flutterfire_auth_dart: ^0.1.1-dev.0
  flutterfire_core_dart: ^0.1.1-dev.0
  meta: ^1.3.0

dev_dependencies:
  async:
  firebase_core_platform_interface:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  plugin_platform_interface:
  
flutter:
  plugin:
    implements: firebase_auth
    platforms:
      macos:
        dartPluginClass: FirebaseAuthDesktop
        pluginClass: none
      linux:
        dartPluginClass: FirebaseAuthDesktop
        pluginClass: none
      windows:
        dartPluginClass: FirebaseAuthDesktop
        pluginClass: none

