name: firebase_auth_desktop
description: Desktop implementation of firebase_auth
homepage: https://firebase.flutter.dev
repository: https://github.com/invertase/flutterfire_dart
version: 0.1.1-dev.3

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  firebase_auth: ^3.2.0
  firebase_auth_dart: ^0.1.1-dev.2
  firebase_auth_platform_interface: ^6.1.4
  firebase_core: ^1.10.0
  firebase_core_dart: ^0.1.1-dev.2
  flutter:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  async: ^2.8.1
  firebase_core_platform_interface: ^4.2.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  plugin_platform_interface: ^2.0.2

flutter:
  plugin:
    implements: firebase_auth
    platforms:
      macos:
        dartPluginClass: FirebaseAuthDesktop
        pluginClass: none
      linux:
        dartPluginClass: FirebaseAuthDesktop
        pluginClass: none
      windows:
        dartPluginClass: FirebaseAuthDesktop
        pluginClass: none
