name: firebase_auth_desktop
description: TODO
homepage: https://firebase.flutter.dev
repository: https://github.com/invertase/flutterfire_dart
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  firebase_auth_dart:
    git:
      url: ssh://git@github.com/invertase/flutterfire_dart
      path: packages/firebase_auth/firebase_auth_dart
      ref: main
  firebase_auth_platform_interface: ^6.1.1
  firebase_core:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  
dev_dependencies:
  firebase_auth:
    git:
      url: git://github.com/pr-Mais/flutterfire
      path: packages/firebase_auth/firebase_auth
      ref: "@mais/firebase-dart"
  
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

dependency_overrides:
  firebase_core:
    git:
      url: git://github.com/pr-Mais/flutterfire
      path: packages/firebase_core/firebase_core
      ref: "@mais/firebase-dart"

flutter:
  plugin:
    platforms:
      linux:
        dartPluginClass: FirebaseAuthDart
        pluginClass: none
      windows:
        dartPluginClass: FirebaseAuthDart
        pluginClass: none
      # testing, later will be removed
      macos:
        dartPluginClass: FirebaseAuthDart
        pluginClass: none
