name: firebase_auth_dart
description: Pure Dart implementation of FlutterFire Auth API
homepage: https://firebase.flutter.dev
repository: https://github.com/invertase/flutterfire_desktop
version: 1.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  firebase_core_dart: ^1.0.1
  firebaseapis: ^0.1.1
  googleapis_auth: ^1.1.0
  http: ^0.13.4
  meta: ^1.3.0
  storagebox: ^0.1.0+2

dev_dependencies:
  async: ^2.8.1
  build_runner: ^2.1.5
  mockito: ^5.0.16
  test: ^1.16.0

false_secrets:
  - /example/bin/firebase_auth_dart_example.dart
  - /test/firebase_auth_dart_test.dart
