name: firebase_auth_dart
description: TODO
homepage: https://firebase.flutter.dev
repository: https://github.com/invertase/flutterfire_dart
version: 0.1.1-dev.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  firebase_core_dart: ^0.1.1-dev.1
  googleapis: ^5.0.1
  googleapis_auth: ^1.1.0
  http: ^0.13.4
  meta: ^1.3.0

dev_dependencies:
  async: ^2.8.1
  build_runner: ^2.1.5
  mockito: ^5.0.16
  test: ^1.16.0
