name: firebase_functions_dart
description: Pure Dart implementation of FlutterFire CloudFunctions API.
homepage: https://firebase.flutter.dev
repository: https://github.com/invertase/flutterfire_dart
version: 0.1.0-dev.4

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  firebase_auth_dart: ^0.1.1-dev.4
  firebase_core_dart: ^0.1.1-dev.2
  http: ^0.13.4
  meta: ^1.7.0

dev_dependencies:
  test: ^1.16.0

false_secrets:
  - /test/firebase_functions_integration_test.dart
  - /test/firebase_functions_test.dart
