
name: firebase_core_dart
description: TODO
homepage: https://firebase.flutter.dev
repository: https://github.com/invertase/flutterfire_dart
version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  firebase_core_platform_interface: ^4.0.1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      linux:
        dartPluginClass: FirebaseCoreDart
        pluginClass: none
      windows:
        dartPluginClass: FirebaseCoreDart
        pluginClass: none
      macos:
        dartPluginClass: FirebaseCoreDart
        pluginClass: none